name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Build-CC:
    runs-on: linux-x86-n2-32
    container:
      image: us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build:latest
    steps:
    - run: echo "ðŸŽ‰ This job uses runner scale set runners!"
